// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSn_73_LMQuI4yuBaMnNVzedR7BD3I7BQ',
    appId: '1:610949937862:web:acfe2c106cc57d7864b5c7',
    messagingSenderId: '610949937862',
    projectId: 'miral-with-mathematics',
    authDomain: 'miral-with-mathematics.firebaseapp.com',
    storageBucket: 'miral-with-mathematics.firebasestorage.app',
    measurementId: 'G-YTVLBLDCDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSM4CLvnOFRsB5GlV1tK3M6dZirMOeRqU',
    appId: '1:610949937862:android:798b2119a4a12b1764b5c7',
    messagingSenderId: '610949937862',
    projectId: 'miral-with-mathematics',
    storageBucket: 'miral-with-mathematics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC56nZYK5QM257lCZdkeY0CBtYSNscw-0',
    appId: '1:610949937862:ios:ec69a47bd4774de164b5c7',
    messagingSenderId: '610949937862',
    projectId: 'miral-with-mathematics',
    storageBucket: 'miral-with-mathematics.firebasestorage.app',
    iosBundleId: 'com.example.miralWithMathematics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC56nZYK5QM257lCZdkeY0CBtYSNscw-0',
    appId: '1:610949937862:ios:ec69a47bd4774de164b5c7',
    messagingSenderId: '610949937862',
    projectId: 'miral-with-mathematics',
    storageBucket: 'miral-with-mathematics.firebasestorage.app',
    iosBundleId: 'com.example.miralWithMathematics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSn_73_LMQuI4yuBaMnNVzedR7BD3I7BQ',
    appId: '1:610949937862:web:ae0f6e46f35189b764b5c7',
    messagingSenderId: '610949937862',
    projectId: 'miral-with-mathematics',
    authDomain: 'miral-with-mathematics.firebaseapp.com',
    storageBucket: 'miral-with-mathematics.firebasestorage.app',
    measurementId: 'G-QCHL9LFKTG',
  );
}
